modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="infinite_power"
version="0.1"
displayName="Infinite Power"
logoFile="landskape.png"
credits=""
authors="RINGULARITY"
description='''
Reach the endlessness.
'''